name: publish macos demo

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  macos-intel-build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Make directories
        run: |
          mkdir -p upload
          mkdir -p ./dist/Intel/VirtualStreetSnap.app/Contents/MacOS

      - name: Get version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=0.0.1" >> $GITHUB_OUTPUT
          fi

      - name: Publish macOS (Intel)
        run: dotnet publish ./src/VirtualStreetSnap -c Release -r osx-x64 --self-contained true -o ./dist/Intel/VirtualStreetSnap.app/Contents/MacOS

      - name: Create Info.plist (Intel)
        run: |
          cat > ./dist/Intel/VirtualStreetSnap.app/Contents/Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleExecutable</key>
              <string>VirtualStreetSnap</string>
              <key>CFBundleName</key>
              <string>VirtualStreetSnap</string>
              <key>CFBundleIdentifier</key>
              <string>com.yourcompany.virtualstreetsnap</string>
              <key>CFBundleShortVersionString</key>
              <string>${{ steps.get_version.outputs.version }}</string>
              <key>CFBundleVersion</key>
              <string>${{ steps.get_version.outputs.version }}</string>
              <key>LSMinimumSystemVersion</key>
              <string>10.12</string>
              <key>NSHighResolutionCapable</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Sign App Bundle (Intel)
        run: |
          codesign --force --deep --sign - ./dist/Intel/VirtualStreetSnap.app

      - name: Create DMG (Intel)
        run: |
          create-dmg \
            --volname "VirtualStreetSnap ${{ steps.get_version.outputs.version }}" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "VirtualStreetSnap.app" 200 190 \
            --hide-extension "VirtualStreetSnap.app" \
            --app-drop-link 600 185 \
            ./upload/VirtualStreetSnap-${{ steps.get_version.outputs.version }}.Intel.dmg \
            ./dist/Intel

      - name: Sign DMG (Intel)
        run: |
          codesign --force --sign - ./upload/VirtualStreetSnap-${{ steps.get_version.outputs.version }}.Intel.dmg

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: VirtualStreetSnap-${{ steps.get_version.outputs.version }}-mac-Intel
          path: ./upload/VirtualStreetSnap-${{ steps.get_version.outputs.version }}.Intel.dmg

  macos-silicon-build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Make directories
        run: |
          mkdir -p upload
          mkdir -p ./dist/AppleSilicon/VirtualStreetSnap.app/Contents/MacOS

      - name: Get version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=0.0.1" >> $GITHUB_OUTPUT
          fi

      - name: Publish macOS (Apple Silicon)
        run: dotnet publish ./src/VirtualStreetSnap -c Release -r osx-arm64 --self-contained true -o ./dist/AppleSilicon/VirtualStreetSnap.app/Contents/MacOS

      - name: Create Info.plist (Apple Silicon)
        run: |
          cat > ./dist/AppleSilicon/VirtualStreetSnap.app/Contents/Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleExecutable</key>
              <string>VirtualStreetSnap</string>
              <key>CFBundleName</key>
              <string>VirtualStreetSnap</string>
              <key>CFBundleIdentifier</key>
              <string>com.yourcompany.virtualstreetsnap</string>
              <key>CFBundleShortVersionString</key>
              <string>${{ steps.get_version.outputs.version }}</string>
              <key>CFBundleVersion</key>
              <string>${{ steps.get_version.outputs.version }}</string>
              <key>LSMinimumSystemVersion</key>
              <string>10.12</string>
              <key>NSHighResolutionCapable</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Sign App Bundle (Apple Silicon)
        run: |
          codesign --force --deep --sign - ./dist/AppleSilicon/VirtualStreetSnap.app

      - name: Create DMG (Apple Silicon)
        run: |
          create-dmg \
            --volname "VirtualStreetSnap ${{ steps.get_version.outputs.version }}" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "VirtualStreetSnap.app" 200 190 \
            --hide-extension "VirtualStreetSnap.app" \
            --app-drop-link 600 185 \
            ./upload/VirtualStreetSnap-${{ steps.get_version.outputs.version }}.AppleSilicon.dmg \
            ./dist/AppleSilicon

      - name: Sign DMG (Apple Silicon)
        run: |
          codesign --force --sign - ./upload/VirtualStreetSnap-${{ steps.get_version.outputs.version }}.AppleSilicon.dmg

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: VirtualStreetSnap-${{ steps.get_version.outputs.version }}-mac-AppleSilicon
          path: ./upload/VirtualStreetSnap-${{ steps.get_version.outputs.version }}.AppleSilicon.dmg 