name: publish macos demo

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  macos-intel-build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Make upload directory
        run: mkdir upload

      - name: Publish macOS (Intel)
        run: dotnet publish ./src/VirtualStreetSnap -c Release -r osx-x64 --self-contained true -o ./dist/Intel

      - name: Archive macOS Build
        run: |
          cd ./dist/Intel && zip -r ../../upload/VirtualStreetSnap.Intel.zip ./*

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: VirtualStreetSnap-mac-Intel
          path: ./upload/VirtualStreetSnap.Intel.zip

  macos-silicon-build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Make upload directory
        run: mkdir upload

      - name: Publish macOS (Apple Silicon)
        run: dotnet publish ./src/VirtualStreetSnap -c Release -r osx-arm64 --self-contained true -o ./dist/AppleSilicon

      - name: Archive macOS Build
        run: |
          cd ./dist/AppleSilicon && zip -r ../../upload/VirtualStreetSnap.AppleSilicon.zip ./*

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: VirtualStreetSnap-mac-AppleSilicon
          path: ./upload/VirtualStreetSnap.AppleSilicon.zip 