name: publish demo

on:
  push:
    branches: [ "master","develop" ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Make upload directory
        run: mkdir upload

      - name: Publish Windows
        run: dotnet publish ./src/VirtualStreetSnap -c Release -r win-x64 --self-contained true -p:PublishAot=true
        
      - name: Archive Windows Build
        run: |
          $files = Get-ChildItem -Path ./src/VirtualStreetSnap/bin/Release/net8.0/win-x64/publish/* -Recurse -Exclude *.pdb
          Compress-Archive -Path $files.FullName -DestinationPath ./upload/VirtualStreetSnap.win-x64.zip
          
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: VirtualStreetSnap-win-x64
          path: ./upload/VirtualStreetSnap.win-x64.zip

  macos-build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Make upload directory
        run: mkdir upload

      - name: Publish macOS
        run: dotnet publish ./src/VirtualStreetSnap -c Release -r osx-x64 --self-contained true
        
      - name: Archive macOS Build
        run: |
          cd ./src/VirtualStreetSnap/bin/Release/net8.0/osx-x64/publish/
          zip -r ../../../../../../upload/VirtualStreetSnap.osx-x64.zip . -x "*.pdb"

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: VirtualStreetSnap-osx-x64
          path: ./upload/VirtualStreetSnap.osx-x64.zip